version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: proshop-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      proshop-network:
        aliases:
          - mongo

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: proshop-backend
    restart: always
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/proshop
      JWT_SECRET: abc123
      PAYPAL_CLIENT_ID: sb
    depends_on:
      - mongo
    networks:
      proshop-network:
        aliases:
          - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proshop-frontend
    restart: always
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      proshop-network:
        aliases:
          - frontend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: proshop-nginx
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - backend
    networks:
      - proshop-network

volumes:
  mongo-data:

networks:
  proshop-network:
    driver: bridge
