server {
    listen 80;

    # Redirection vers le Frontend React
    location / {
        proxy_pass http://proshop-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Redirection vers le Backend Node.js
    location /api {
        proxy_pass http://proshop-backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}